# Generated by Django 5.0.1 on 2024-01-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Username',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default='none', max_length=100),
        ),
    ]
