# Generated by Django 5.0.1 on 2024-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_body_post_created_at_post_no_of_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
